# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_squashed_0028_auto_20171113_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproductivitylog',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sleeplog',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='supplementlog',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usermoodlog',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
