# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupplementProductEventComposition',
            new_name='SupplementEvent',
        ),
    ]
