# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-24 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_switch_to_decimal_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplementevent',
            unique_together=set([('user', 'time', 'supplement')]),
        ),
    ]
