# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-15 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160810_2348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplementevent',
            options={'verbose_name': 'Supplement Event', 'verbose_name_plural': 'Supplement Events'},
        ),
    ]
