# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-24 14:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_add_unique_constraints_of_time_and_supplement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProductivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source', models.CharField(choices=[('api', 'Api'), ('ios', 'Ios'), ('android', 'Android'), ('web', 'Web'), ('user_excel', 'User_Excel')], max_length=50)),
                ('day', models.DateField()),
                ('very_productive_time_minutes', models.PositiveIntegerField()),
                ('productive_time_minutes', models.PositiveIntegerField()),
                ('neutral_time_minutes', models.PositiveIntegerField()),
                ('distracting_time_minutes', models.PositiveIntegerField()),
                ('very_distracting_time_minutes', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sleepeventlog',
            unique_together=set([('day', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='dailyproductivitylog',
            unique_together=set([('day', 'user')]),
        ),
    ]
