# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-24 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20161215_0357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplementevent',
            options={'ordering': ['user', '-time'], 'verbose_name': 'Supplement Event', 'verbose_name_plural': 'Supplement Events'},
        ),
    ]
