# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-26 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_productive_models_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyproductivitylog',
            name='distracting_time_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyproductivitylog',
            name='neutral_time_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyproductivitylog',
            name='productive_time_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyproductivitylog',
            name='very_distracting_time_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyproductivitylog',
            name='very_productive_time_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
