# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-01 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_ordering_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepeventlog',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='supplementevent',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
