# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-26 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_null_true_for_productive_logs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyproductivitylog',
            options={'ordering': ['-day']},
        ),
    ]
