# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-27 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_productive_log_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyproductivitylog',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='dailyproductivitylog',
            old_name='day',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='sleepeventlog',
            old_name='day',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='dailyproductivitylog',
            unique_together=set([('date', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='sleepeventlog',
            unique_together=set([('date', 'user')]),
        ),
    ]
