# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-05 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_switch_day_to_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyproductivitylog',
            options={'ordering': ['-date'], 'verbose_name': 'Daily Productivity Log', 'verbose_name_plural': 'Daily Productivity Logs'},
        ),
    ]
