# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-19 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20170205_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplementevent',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
