# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-21 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_supplementevent_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyproductivitylog',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sleepeventlog',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='supplementevent',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
