# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-29 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_rename_user_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivityevent',
            options={'ordering': ['user', '-time']},
        ),
    ]
