# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_sleepactivitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['name']},
        ),
    ]
