# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20170618_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sleepactivitylog',
            options={'ordering': ['user', '-end_time'], 'verbose_name': 'Sleep Activity Log', 'verbose_name_plural': 'Sleep Activity Logs'},
        ),
    ]
