# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20170618_1021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SleepActivityLog',
            new_name='SleepActivity',
        ),
    ]
