# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20170626_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='is_all_day_activity',
            field=models.BooleanField(default=False),
        ),
    ]
