# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_useractivity_is_all_day_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplementevent',
            name='source',
            field=models.CharField(choices=[('api', 'Api'), ('ios', 'Ios'), ('android', 'Android'), ('web', 'Web'), ('user_excel', 'User_Excel')], default='web', max_length=50),
        ),
    ]
