# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 22:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0003_data_migrations_for_measurements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0021_auto_20170905_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplementReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('time', models.DateTimeField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplements.Supplement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='supplementreminder',
            unique_together=set([('user', 'supplement', 'time')]),
        ),
    ]
