# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_rename_user_activity_event_to_log'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SleepActivity',
            new_name='SleepLog',
        ),
    ]
