# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_sleep_activity_rename'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupplementEvent',
            new_name='SupplementLog',
        ),
    ]
