# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 01:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0026_rename_productivity_event_to_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMoodLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('time', models.TimeField()),
                ('value', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('api', 'Api'), ('ios', 'Ios'), ('android', 'Android'), ('web', 'Web'), ('user_excel', 'User_Excel'), ('text_message', 'Text_Message')], default='web', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mood Log',
                'verbose_name_plural': 'Mood Logs',
            },
        ),
        migrations.AlterUniqueTogether(
            name='usermoodlog',
            unique_together=set([('user', 'time')]),
        ),
    ]
