# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 03:32
from __future__ import unicode_literals

import betterself.utils.date_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_add_user_mood'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermoodlog',
            options={'ordering': ['user', '-time'], 'verbose_name': 'Mood Log', 'verbose_name_plural': 'Mood Logs'},
        ),
        migrations.AlterField(
            model_name='usermoodlog',
            name='time',
            field=models.DateTimeField(default=betterself.utils.date_utils.get_current_utc_time_and_tz),
        ),
    ]
