# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0001_squashed_0007_auto_20171023_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplement',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
