# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-24 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0002_data_migration_for_measurement_units'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeasurementUnit',
            new_name='Measurement',
        ),
        migrations.RenameModel(
            old_name='SupplementProduct',
            new_name='Supplement',
        ),
    ]
