# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0003_auto_20160724_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplement',
            old_name='ingredient_composition',
            new_name='ingredient_compositions',
        ),
    ]
