# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def load_data(apps, schema_editor):
        app = apps.get_model("supplements", "MeasurementUnit")

        # pycharm is amazing.
        dict_list = [
            {
                'name': 'milligram',
                'short_name': 'mg',
                'is_liquid': False,
            },
            {
                'name': 'gram',
                'short_name': 'g',
                'is_liquid': False,
            },
            {
                'name': 'milliliter',
                'short_name': 'ml',
                'is_liquid': True,
            },
            {
                'name': 'liter',
                'short_name': 'l',
                'is_liquid': True,
            },
        ]

        for measurement in dict_list:
            app.objects.create(**measurement)



    dependencies = [
        ('supplements', '0003_auto_20160528_1519'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
