# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-30 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0004_auto_20160727_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientcomposition',
            name='measurement_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplements.Measurement'),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='ingredient_compositions',
            field=models.ManyToManyField(blank=True, to='supplements.IngredientComposition'),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor'),
        ),
    ]
