# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 04:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplements', '0004_auto_20171019_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSupplementStackComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.FloatField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='usersupplementstack',
            name='supplements',
        ),
        migrations.AddField(
            model_name='usersupplementstackcomposition',
            name='stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplements.UserSupplementStack'),
        ),
        migrations.AddField(
            model_name='usersupplementstackcomposition',
            name='supplement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplements.Supplement'),
        ),
        migrations.AddField(
            model_name='usersupplementstackcomposition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usersupplementstackcomposition',
            unique_together=set([('supplement', 'stack')]),
        ),
    ]
