# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 04:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplements', '0006_auto_20171022_0700'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersupplementstackcomposition',
            unique_together=set([('user', 'supplement', 'stack')]),
        ),
    ]
