# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-15 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0006_auto_20160802_1205'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientcomposition',
            unique_together=set([('user', 'ingredient', 'measurement', 'quantity')]),
        ),
    ]
