# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-15 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0008_auto_20161215_0223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientcomposition',
            options={'ordering': ['user', 'ingredient__name']},
        ),
        migrations.AlterModelOptions(
            name='supplement',
            options={'ordering': ['user', 'name']},
        ),
    ]
