# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-24 20:02
from __future__ import unicode_literals

from django.db import migrations
import logging

logger = logging.getLogger(__name__)


class Migration(migrations.Migration):
    def load_data(apps, schema_editor):
        User = apps.get_model('users', 'User')
        default_user, _ = User.objects.get_or_create(username='default')
        logger.info('{user} was successfully created'.format(user=default_user))

    dependencies = [
        ('users', '0004_user_uuid'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
