# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170617_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demouserlog',
            options={'verbose_name': 'Demo User Log', 'verbose_name_plural': 'Demo User Logs'},
        ),
    ]
