# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userphonenumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userphonenumber',
            options={'verbose_name': 'User Phone Number', 'verbose_name_plural': 'User Phone Numbers'},
        ),
    ]
