# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 02:12
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20171003_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphonenumber',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True),
        ),
    ]
