# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20171005_0212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPhoneNumber',
            new_name='UserPhoneNumberDetails',
        ),
    ]
