export const HOME_URL = '/'
export const DASHBOARD_OVERVIEW_URL = '/dashboard/overview/'
export const DASHBOARD_INDEX_URL = '/dashboard/index'
// this should eventually be just '/login'
export const LOGIN_URL = '/login'
