export const HOME_URL = '/'
export const DASHBOARD_OVERVIEW_URL = '/dashboard/overview/'
export const DASHBOARD_INDEX_URL = '/dashboard/index'
export const LOGIN_URL = '/login'
export const LOGOUT_URL = '/dashboard/logout'
export const SETTINGS_URL = '/login/settings'
