# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 03:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeriesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date the data was recorded')),
                ('value', models.CharField(default=None, help_text='The value of the data. This is typically a number, though saved as a string here. The units can be inferred from the data type. For example, for step data the value might be "9783" (the units) would be "steps"', max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSeriesDataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(0, 'foods'), (1, 'activities'), (2, 'sleep'), (3, 'body')])),
                ('resource', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['category', 'resource'],
            },
        ),
        migrations.CreateModel(
            name='UserFitbit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitbit_user', models.CharField(max_length=32, unique=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='timeseriesdatatype',
            unique_together=set([('category', 'resource')]),
        ),
        migrations.AddField(
            model_name='timeseriesdata',
            name='resource_type',
            field=models.ForeignKey(help_text='The type of time series data', on_delete=django.db.models.deletion.CASCADE, to='fitbit.TimeSeriesDataType'),
        ),
        migrations.AddField(
            model_name='timeseriesdata',
            name='user',
            field=models.ForeignKey(help_text="The data's user", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='timeseriesdata',
            unique_together=set([('user', 'resource_type', 'date')]),
        ),
    ]
