# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0003_auto_20170822_0324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfitbit',
            old_name='fitbit_user',
            new_name='fitbit_user_id',
        ),
    ]
