# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-01 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendor_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
