# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 05:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betterselfcredentials',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fitbitapicredentials',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rescuetimeapicredentials',
            name='user',
        ),
        migrations.DeleteModel(
            name='BetterSelfCredentials',
        ),
        migrations.DeleteModel(
            name='FitBitAPICredentials',
        ),
        migrations.DeleteModel(
            name='RescueTimeAPICredentials',
        ),
    ]
